version: 0.0
os: linux
files:
    - source: scripts
      destination: /home/ec2-user/deploy-scripts
      ApplicationStart:
        - location: scripts/deploy.sh
          timeout: 300
          runas: root    
