name: Database pipeline
on:
  push:
    branches: [ main ]
    paths: 
      - '/database'
  workflow_dispatch:
jobs:
  build-and-push:
        runs-on: ubuntu-latest
        defaults:
         run:
           working-directory: 'database/**'
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: configure aws
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY}}
                aws-region: ${{secrets.AWS_REGION}}
            - name: login to ecr
              id: ecr-login
              uses: aws-actions/amazon-ecr-login@v2
            - name: build and push to ecr
              env:
                REGISTORY: ${{steps.ecr-login.outputs.registry}}
                REPOSITORY: book-inventory/book-inventory-db
                TAG: latest
              run: |
                docker build -t $REGISTORY/$REPOSITORY:$TAG .
                docker push $REGISTORY/$REPOSITORY:$TAG
  deploy: 
      needs: build-and-push    
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: 'database/**'
      steps:
        - name: login to db server
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.DB_VM_HOST}}
            username: ${{ secrets.DB_VM_USER}}
            password: ${{secrets.DB_VM_KEY}}
            port: ${{secrets.PORT}}
            script:  |
              echo "login successfull"
        

