name: frontend pipeline
on: 
  push:
     branches: 
       -  main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
     - name: checkout the code
       uses: actions/checkout@v4
     - name: setup node
       uses: actions/setup-node@v6
       with:
         version: '20'
     - name: install deps
       run: npm install
     - name: run build
       run: npm run build
  test:
    needs: build 
    runs-on: ubuntu-latest
    steps:
     - name: checkout the code
       uses: actions/checkout@v4
     - name: setup node
       uses: actions/setup-node@v6
       with:
         version: '20'
     - name: install deps
       run: npm install
     - name: run test
       run: npm test
  build-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
     - name: checkout the code
       uses: actions/checkout@v4
     - name: configure aws
       uses: aws-actions/configure-aws-credentials@v2
       with:
         aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
         aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY}}
         aws-region: ${{secrets.AWS_REGION}}
     - name: ecr login
       id: ecr-login
         aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
         aws-secret-access-key: ${{secrets.A: aws-actions/amazon-ecr-login@v2
     - name: tag and push to ecr
       env:
        REGISTRY: ${{steps.ecr-login.outputs.registry}}
        REPOSITORY: book-inventory/book-inventory-frontend
        TAG: latest
       run:  |
        docker build -t $REGISTRY/$REPOSITORY:$TAG .
        docker push  $REGISTRY/$REPOSITORY:$TAG
  deploy:
     needs: build-push
     runs-on: ubuntu-latest
     steps:
       - name: checkout code 
         uses: actions/checkout@v4
       - name: login to aws
         uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
           aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY}}
           aws-region: ${{secrets.AWS_REGION}}
       - name: zip the file
         run: zip -r  deploy.zip   appspec.yml  scripts/ 
       - name: upload zip to s3 bucket
         run: |
             aws s3 cp deploy.zip s3://book-inventory-bucket-1 /frontend/deploy.zip
       - name: Trigger AWS CodeDeploy Deployment
         run: |
             aws deploy create-deployment \
             --application-name frontend-da \
             --deployment-group-name forntend-dg \
             --s3-location bucket=book-inventory-bucket-1,key=frontend/deploy.zip,bundleType=zip

